name: CI (Windows Clang)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 'latest'
      
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21.1.3"
          directory: ${{ runner.temp }}/llvm

      - name: CMake configuration
        run: cmake -S . -B Build -G Ninja -D CMAKE_BUILD_TYPE=Debug -D AURA_ENABLE_TESTING=On
        shell: powershell

      - name: Ninja compilation
        run: ninja -C Build
        shell: powershell