name: CI (Windows Clang)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install CMake
        run: Invoke-WebRequest -Uri "https://github.com/Kitware/CMake/releases/download/v4.1.2/cmake-4.1.2-windows-x86_64.zip" -OutFile cmake.zip
        shell: powershell
      
      - name: Extract CMake
        run: Expand-Archive cmake.zip -DestinationPath C:\CMake
        shell: powershell
      
      - name: Add CMake to PATH
        run: echo "C:\CMake\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: powershell
      
      - name: Install LLVM
        run: Invoke-WebRequest -Uri "https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.3/LLVM-21.1.3-win64.exe" -OutFile "LLVM-21.1.3-win64.exe"
        shell: powershell

      - name: Extract LLVM
        run: 7z x LLVM-21.1.3-win64.exe -oC:\LLVM
        shell: powershell

      - name: Add LLVM to PATH
        run: echo "C:\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: powershell

      - name: CMake debug configuration
        run: cmake -S . -B Build -G Ninja -D CMAKE_BUILD_TYPE=Debug -D AURA_ENABLE_TESTING=On
        shell: powershell

      - name: Ninja debug compilation
        run: ninja -C Build
        shell: powershell
      
      - name: CMake release configuration
        run: cmake -S . -B Build -G Ninja -D CMAKE_BUILD_TYPE=Release -D AURA_ENABLE_TESTING=On
        shell: powershell

      - name: Ninja release compilation
        run: ninja -C Build
        shell: powershell